### ISSUE TITLE
running error

### ISSUE THREAD

**Issue by yuzhongduobu** [imatif17/Prototype-Mean-Teacher#5]
RuntimeError: Expected to mark a variable ready only once. This error is caused by one of the following reasons: 1) Use of a module parameter outside the `forward` function. Please make sure model parameters are not shared across multiple concurrent forward-backward passes. or try to use _set_static_graph() as a workaround if this module graph does not change during training loop.2) Reused parameters in multiple reentrant backward passes. For example, if you use multiple `checkpoint` functions to wrap the same part of your model, it would result in the same set of parameters been used by different reentrant backward passes multiple times, and hence marking a variable ready multiple times. DDP does not support such use cases in default. You can try to use _set_static_graph() as a workaround if your module graph does not change over iterations.
Parameter at index 65 has been marked as ready twice. This means that multiple autograd engine  hooks have fired for this particular parameter during this iteration. You can set the environment variable TORCH_DISTRIBUTED_DEBUG to either INFO or DETAIL to print parameter names for further debugging.

**Comment by imatif17** [comment]
Hi,

I'm sorry for not getting back to you sooner.
This error is because in Pytorch (without DDP) it is possible to have a training loop without having gradients of some of the parameters. But, DDP doesn't allow this. There are two ways to fix this - 

1. Calculate the t_losses (line 439 in trainer.py) in the burn-up training. (Not recommended as it wastes a lot of resources).
2. Don't initialize the prototype layer and train the model in the burn-up stage. After that initialize the prototype layer, and do the prototype learning training. (Recommended)

I know the solution sounds weird but that's how Pytorch DDP works. Also, please check the code of our new method ACIA for refernce, where we fixed this issue - [https://github.com/imatif17/ACIA](https://github.com/imatif17/ACIA)
