### ISSUE TITLE
Confused about the contrast loss of prototype_s1 instead of prototype_s2

### ISSUE THREAD

**Issue by Bradly-s** [imatif17/Prototype-Mean-Teacher#8]
In branch == "prototype_all", why calculate the contrast loss of prototype_s1 instead of prototype_s2?

 loss_c = 0
            if self.contra:
                for i, j in itertools.combinations(list(range(len(self.prototype_s1))),2):
                    loss_c += F.cosine_similarity(self.prototype_s1[i].view(-1,1), self.prototype_s1[j].view(-1,1)).abs().mean().to(self.device)
                loss_c = loss_c/math.comb(len(self.prototype_s1), 2)
                self.prototype_s1.detach_()

**Comment by imatif17** [comment]
Hi,

I did it because adding prototype_s2 was destabilizing the training in the case of Cross-Time Setting. This is probably because of the huge domain shift between Source 2 and Target (Night and Dusk/Dawn). I tried visualizing a TSNE plot of this scenario, it was aligned well between S1 and T. But S2 was very wayward. That's why I removed S2 in this case. In general cases (Apart from some special case like cross-time) I don't think having S2 here will be a problem. But, I think it's better to align the source domain which is more closer to the target domain.
